import pg from 'pg'
const c = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } })
await c.connect()
const q = (sql, p) => c.query(sql, p).then(r => r.rows)
const rs = v => 'Rs ' + (Number(v)/100).toFixed(2)
const n  = v => Number(v)

const [{id:org}] = await q("select id from organizations where name='Demo Traders'")

const [tb]     = await q('select sum(debit)::bigint dr, sum(credit)::bigint cr from ledger_entries le join accounts a on a.id=le.account_id where a.org_id=$1',[org])
const [ar]     = await q("select coalesce(sum(le.debit-le.credit),0)::bigint bal from ledger_entries le join accounts a on a.id=le.account_id where le.org_id=$1 and a.parent_id=(select id from accounts where org_id=$1 and system_key='debtors')",[org])
const [ap]     = await q("select coalesce(sum(le.credit-le.debit),0)::bigint bal from ledger_entries le join accounts a on a.id=le.account_id where le.org_id=$1 and a.parent_id=(select id from accounts where org_id=$1 and system_key='creditors')",[org])
const [inv]    = await q('select count(*)::int n, sum(outstanding)::bigint s from invoices where org_id=$1',[org])
const [bil]    = await q('select count(*)::int n, sum(outstanding)::bigint s from bills where org_id=$1',[org])
const [dash]   = await q('select receivables::bigint rec, payables::bigint pay, cash_balance::bigint cash, bank_balance::bigint bank from v_dashboard_summary where org_id=$1',[org])
const [agedr]  = await q('select sum(outstanding)::bigint tot from v_aged_receivables where org_id=$1',[org])
const [agedp]  = await q('select sum(outstanding)::bigint tot from v_aged_payables where org_id=$1',[org])
// voucher_type 7=CREDIT_NOTE, 8=DEBIT_NOTE
const cn       = await q("select coalesce(sum(le.credit-le.debit),0)::bigint tot from ledger_entries le join accounts a on a.id=le.account_id join vouchers v on v.id=le.voucher_id where le.org_id=$1 and a.parent_id=(select id from accounts where org_id=$1 and system_key='debtors') and v.voucher_type=7",[org])
const dn       = await q("select coalesce(sum(le.debit-le.credit),0)::bigint tot from ledger_entries le join accounts a on a.id=le.account_id join vouchers v on v.id=le.voucher_id where le.org_id=$1 and a.parent_id=(select id from accounts where org_id=$1 and system_key='creditors') and v.voucher_type=8",[org])

const ok = (label, pass) => console.log(`  ${pass ? '✓' : '✗'} ${label}`)

console.log('\n══ AUDIT: Demo Traders ══════════════════════\n')
console.log('1. TRIAL BALANCE')
console.log('   DR =', rs(tb.dr))
console.log('   CR =', rs(tb.cr))
ok('DR = CR (double-entry intact)', BigInt(tb.dr) === BigInt(tb.cr))

console.log('\n2. RECEIVABLES')
console.log('   GL debtors balance   =', rs(ar.bal))
console.log('   Dashboard receivables=', rs(dash.rec))
console.log('   Aged rec total       =', rs(agedr.tot))
console.log('   invoices.outstanding =', rs(inv.s), `(${inv.n} invoices)`)
console.log('   Credit notes in GL   =', rs(cn[0].tot))
console.log('   inv.out − CN         =', rs(n(inv.s) - n(cn[0].tot)))
ok('GL debtors = Dashboard', n(ar.bal) === n(dash.rec))
ok('GL debtors = Aged receivables total', n(ar.bal) === n(agedr.tot))
ok('inv.outstanding − credit_notes = GL', (n(inv.s) - n(cn[0].tot)) === n(ar.bal))

console.log('\n3. PAYABLES')
console.log('   GL creditors balance =', rs(ap.bal))
console.log('   Dashboard payables   =', rs(dash.pay))
console.log('   Aged pay total       =', rs(agedp.tot))
console.log('   bills.outstanding    =', rs(bil.s), `(${bil.n} bills)`)
console.log('   Debit notes in GL    =', rs(dn[0].tot))
console.log('   bil.out − DN         =', rs(n(bil.s) - n(dn[0].tot)))
ok('GL creditors = Dashboard', n(ap.bal) === n(dash.pay))
ok('GL creditors = Aged payables total', n(ap.bal) === n(agedp.tot))
ok('bil.outstanding − debit_notes = GL', (n(bil.s) - n(dn[0].tot)) === n(ap.bal))

console.log('\n4. CASH & BANK')
console.log('   Cash =', rs(dash.cash), '  Bank =', rs(dash.bank))
ok('Cash not negative', n(dash.cash) >= 0)
ok('Bank not negative', n(dash.bank) >= 0)

console.log('\n══ SUMMARY ══════════════════════════════════')
console.log('   Cash in hand :', rs(dash.cash))
console.log('   Bank balance :', rs(dash.bank))
console.log('   Receivables  :', rs(dash.rec), `— ${inv.n} invoices`)
console.log('   Payables     :', rs(dash.pay), `— ${bil.n} bills`)
console.log('═════════════════════════════════════════════\n')

await c.end()
